
##House Seeding

House.create!(name: "Gryffindor", motto: "You might belong in Gryffindor, Where dwell the brave at heart, Their daring, nerve and chivalry Set Gryffindors apart.", description: "
Gryffindor values courage, bravery, nerve and chivalry. Its mascot is the lion, and its colours are scarlet and gold. The Gryffindor motto is 'Their daring, nerve and chivalry set Gryffindors apart'. The Head of this house is the Transfiguration teacher and Deputy Headmistress, Minerva McGonagall, and the house ghost is Sir Nicholas de Mimsy-Porpington, more commonly known as Nearly Headless Nick. According to Rowling, Gryffindor corresponds roughly to the element of fire. The founder of the house is Godric Gryffindor.

The Gryffindor common room is located in one of the castle's highest towers, the entrance to which is located on the seventh floor in the east wing of the castle and is guarded by a painting of The Fat Lady, who is garbed in a pink dress. She permits entry only after being given the correct password, as was distinguished in the third book, when Sirius Black tried forcing entry into the tower, only to be blocked by The Fat Lady after he could not give the correct password. In the first book, Neville Longbottom tends to forget the password and must wait near the painting until other Gryffindors arrive to open the way.", logo_img_url: "https://harrypottercrazies.weebly.com/uploads/1/8/4/4/18445957/4778832.jpg")

House.create!(name: "Ravenclaw", motto: "Or yet in wise old Ravenclaw, If you've a ready mind, Where those of wit and learning, Will always find their kind.", description: "
Ravenclaw values intelligence, creativity, learning, and wit. The house mascot is an eagle and the house colours are blue and bronze (blue and grey in the films). The Ravenclaw motto is 'Wit beyond measure is man's greatest treasure'. The head of this house is the Charms professor, Filius Flitwick, and the house ghost is The Grey Lady. According to Rowling, Ravenclaw corresponds roughly to the element of air. The founder of this house is Rowena Ravenclaw.

The dormitories are located in Ravenclaw Tower, on the west side of Hogwarts. The common room, which went undescribed in the series until the climax of Deathly Hallows, is round and filled with blue hangings and armchairs, has a domed ceiling painted with stars and features a replica statue of Rowena wearing her diadem. Harry also notes that Ravenclaws 'have a spectacular view of the surrounding mountains'. A logical riddle must be solved to gain entry, whereas the Gryffindor and Slytherin common rooms only require a password (Hufflepuffs need to tap a barrel in the rhythm of 'Helga Hufflepuff'), indicating that it may be easier for those students from other houses who possess a high degree of intelligence to enter this common room than others. Professor McGonagall, the head of the Gryffindor House, solves the riddle accurately.", logo_img_url: "https://harrypottercrazies.weebly.com/uploads/1/8/4/4/18445957/1177755.jpg?264")

House.create!(name: "Slytherin", motto: "Or perhaps in Slytherin You'll make your real friends Those cunning folk use any means to achieve their ends.", description: "
Slytherin house values ambition, cunning, leadership, and resourcefulness; the Sorting Hat said in Harry Potter and the Philosopher's Stone that Slytherins will do anything to get their way. The house mascot of Slytherin is the serpent, and the house colours are green and silver. The Slytherin motto is 'Slytherin will help you on your way to greatness'. Salazar Slytherin founded the house. The Head of House is Severus Snape until near the end of the sixth book. Then, Horace Slughorn, the previous Head of House, comes out of retirement re-assuming authority. The ghost of Slytherin house is The Bloody Baron. According to Rowling, Slytherin corresponds roughly to the element of water. The Slytherin dormitories and common room are reached through a bare stone wall in the dungeons. The Slytherin common room is a long, low, dungeon-style room, located under the Hogwarts Lake, furnished with green lamps and carved armchairs. The room is described in the second book as having a greenish glow.

The Sorting Hat claims that blood purity is a factor in selecting Slytherins, although this is not mentioned until the fifth book. There is no reason to believe, however, that Muggle-born students are not sorted there, merely that pure-blooded students are more desirable to that house, as there are several examples of half-bloods in the house (such as Snape and Voldemort). In Deathly Hallows, a group of Snatchers claim that 'not many Mudbloods' are sorted into Slytherin.", logo_img_url: "https://harrypottercrazies.weebly.com/uploads/1/8/4/4/18445957/987119.jpg?250")

House.create!(name: "Hufflepuff", motto: "You might belong in Hufflepuff, Where they are just and loyal, Those patient Hufflepuffs are true And unafraid of toil.", description: "
Hufflepuff values hard work, patience, justice, and loyalty. The house mascot is the badger, and canary yellow and black are its colours. The Hufflepuff motto is 'Those patient Hufflepuffs are true and unafraid of toil'. The Head of this house is the Herbology teacher Pomona Sprout, and t'e house ghost is The Fat Friar. According to Rowling, Hufflepuff corresponds roughly to the element of earth. The founder of this house is Helga Hufflepuff.

The Hufflepuff dormitories and common room entrance 'is concealed in a stack of large barrels in a nook on the right hand side of the kitchen corridor.' To enter, one must tap the barrel two from the bottom in the middle of the second row in the rhythm of 'Helga Hufflepuff'. Unlike any other house, the Hufflepuff common room has a repelling device that douses the illegal entrant in vinegar if the wrong lid is tapped or the rhythm is wrong. The Hufflepuff common room is filled with yellow hangings and fat armchairs and it has little underground tunnels leading to the dormitories, all of which have perfectly round doors, like barrel tops (much like a badger sett)", logo_img_url: "https://harrypottercrazies.weebly.com/uploads/1/8/4/4/18445957/3077859.jpg?303")

## User Seeding

User.create!(name: "Kyle Conlon", username: "KyleConlon", password: "kylespassword", house_id: 2)
User.create!(name: "Rafia Khandaker", username: "RafiaKhandaker", password: "rafiaspassword", house_id: 2)
User.create!(name: "Harry Potter", username: "Expelliarmus4Lyfe", password: "harryspassword", house_id: 1)
User.create!(name: "Draco Malfoy", username: "SnakesRcool23", password: "dracospassword", house_id: 3)
User.create!(name: "Laura Conlon", username: "LauraConlon", password: "lauraspassword", house_id: 4)
User.create!(name: "Linda Conlon", username: "LindaConlon", password: "lindaspassword", house_id: 4)
User.create!(name: "Hermoine Granger", username: "BookWorm21", password: "hermoinespassword", house_id: 1)
User.create!(name: "Dwayne Perry", username: "Dwayne23", password: "dwaynespassword", house_id: 3)

Patronu.create!(animal: "Lion", meaning: "The lion, along with being the mascot of Gryffindor House, is often seen as the “king of beasts.” Lions generally live in close-knit prides, which they are fiercely protective of. They are kind to cubs, sharing their food. These cats are fierce warriors, symbolizing bravery as well as strength and nobility. If your Patronus is the lion, you are likely brave, close to those in your inner circle, and extremely protective. Despite your fierceness when challenged, you have a soft spot for those weaker than yourself for whom you are willing to make sacrifices.", user_id: 2)
Patronu.create!(animal: "Wolf", meaning: "Wolf Patronuses see their casters as part of their pack, and they are ready to defend them at any cost. Wolves have incredible instincts; they will attack all Dementors in the immediate vicinity and hunt down any stragglers remaining at a distance. No Dementor should cross a wolf Patronus – they are fierce protectors and loyal to their casters beyond any other guardian.", user_id: 1)
Patronu.create!(animal: "Stag", meaning: "The stag is a symbol of strength. A person with this Patronus is characterized for their inclination to heroism and nobility. Usually, people who produce this Patronus are confident in their capabilities and hold pride in their actions and beliefs. The stag’s antlers can grow back once they fall off. Because of this characteristic, this animal has been revered in many traditions as a symbol of life regeneration.", user_id: 3)
Patronu.create!(animal: "Shark", meaning: "They are the most feared fish in the ocean and have diversified into over 500 species (two of which can also survive and be found in rivers). People who have this Patronus are known for excelling in business environments, being leaders, and sometimes being a bit intimidating. Also, they tend to have good skin and a great set of teeth.", user_id: 4)

Patronu.create!(animal: "Dolphin", meaning: "Intelligence and sociability are among the main attributes of the dolphin. Also known for their playfulness and loyalty, dolphins live and work together in groups to aid the sick and injured and to defend each other from predators. Its incredible intelligence is put to good use in the form of solving complex problems and other such challenges. The dolphin does not enjoy dull, routine activities, so keeping busy with interesting tasks is a must!", user_id: 5)
Patronu.create!(animal: "Phoenix", meaning: "The only known possessor of this Patronus is Albus Dumbledore. The phoenix is known as the resurrection bird, dying in a glorious pyre of flames and then rising again to new life from the ashes. The phoenix lives to an immense age and can carry very heavy loads, and their tears have healing powers. Phoenixes are hard to domesticate, but they are loyal to their owners for a lifetime. Once their owner dies, they will not seek another master. If you are not Albus Dumbledore and happen to find yourself the possessor of a phoenix Patronus, you are likely stronger spiritually than most anyone else, so much so that your love heals the spirits of those around you. No one can tame you or claim you in any way. You are very much a loner. At the same time, many admire and adore you for your strength, wisdom, and above all, your immense power to love even your enemies. You do not fear death but understand it is the next great adventure, and should you be faced with it, you will greet death like an old friend – especially if it means saving the life of another.", user_id: 6)
Patronu.create!(animal: "Otter", meaning: "Through their affinity to water, otters are symbolic of life and purification. Otters are also extremely playful and curious. They have no reservations about following their curiosity since they are also fearless. Without many enemies in the wild, these little guys don’t have much reason to be afraid. Associated with friendship, otters are often found holding hands while sleeping.", user_id: 7)
Patronu.create!(animal: "Dragon", meaning: "One of the most powerful and formidable creatures of the magical world, dragons are ambitious and dominant. With the ability to breathe fire, they quickly assert themselves, garnering both fear and respect from those around them. They are unafraid to take risks and prefer to live by their own set of rules. They are quick to lead and do not back down from a challenge. Dragons are strong in their convictions and will stand for what they believe is right. Those with a dragon for a Patronus are sure to be fierce fighters, and the Dementors better be ready for a challenge!", user_id: 8)

Spell.create!(name: "Riddikulus", purpose: "Transforms nasty Boggarts from somethings scary into something silly")
Spell.create!(name: "Obliviate", purpose: "A charm to wipe memory")
Spell.create!(name: "Avada Kedavra", purpose: "Kills")
Spell.create!(name: "Alohomora", purpose: "Opens locked doors")
Spell.create!(name: "Lumos", purpose: "Creates light")
Spell.create!(name: "Expelliarmus", purpose: "Disarms your opponent")
Spell.create!(name: "Wingardium Leviosa", purpose: "Makes things levitate")
Spell.create!(name: "Accio", purpose: "Summons objects")
Spell.create!(name: "Expecto Patronum", purpose: "Gets rid of pesky dementors")

Wand.create!(wood: "Cherry", length: "10.5", flexibility: "Slightly bendy", core: "Dragon Heartstring", user_id: 1) 
Wand.create!(wood: "Holly", length: "11", flexibility: "Nice and Supple", core: "Phoenix Feather", user_id: 3) 

Casting.create!(user_id:5, spell_id:1)
Casting.create!(user_id:6, spell_id:2)
Casting.create!(user_id:7, spell_id:3)
Casting.create!(user_id:8, spell_id:4)